---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - client.openstack.org
  resources:
  - openstackclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - client.openstack.org
  resources:
  - openstackclients/finalizers
  verbs:
  - update
- apiGroups:
  - client.openstack.org
  resources:
  - openstackclients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - memcached.openstack.org
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memcached.openstack.org
  resources:
  - memcacheds/finalizers
  verbs:
  - update
- apiGroups:
  - memcached.openstack.org
  resources:
  - memcacheds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - iprequesters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - iprequesters/finalizers
  verbs:
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - iprequesters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - openstackipmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - openstackipmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - openstackipmanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - openstacknetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.openstack.org
  resources:
  - openstacknetworks/finalizers
  verbs:
  - update
- apiGroups:
  - network.openstack.org
  resources:
  - openstacknetworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls/status
  verbs:
  - get
  - patch
  - update
