apiVersion: network.openstack.org/v1beta1
kind: DNSMasq
metadata:
  name: dnsmasq
spec:
  externalEndpoints:
  - ipAddressPool: ctlplane
    loadBalancerIPs:
    - 192.168.111.80
  replicas: 1
  options:
  - key: server
    values:
    - 192.168.111.1
  debug:
    service: false
